      function printTextArea() {
        childWindow = window.open('','childWindow','location=yes, menubar=yes, toolbar=yes');
        childWindow.document.open();
        childWindow.document.writeln('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"'); 				 
		childWindow.document.writeln('"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">');
		childWindow.document.writeln('<html xmlns="http://www.w3.org/1999/xhtml">');
		childWindow.document.writeln('<head>');
		childWindow.document.writeln('<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />');
		childWindow.document.writeln('<title>Untitled Document</title>');
		childWindow.document.writeln('<style type="text/css">');
		childWindow.document.writeln('label textarea {');
		childWindow.document.writeln('	vertical-align: top;');
		childWindow.document.writeln('	text-decoration: underline;');
		childWindow.document.writeln('}');
		childWindow.document.writeln('.form_style {');
		childWindow.document.writeln('	font-family: "Times New Roman", Times, serif;');
		childWindow.document.writeln('	font-weight: bold;');
		childWindow.document.writeln('	font-size: 18px;');
		childWindow.document.writeln('	margin-top: 250px;');
		childWindow.document.writeln('	margin-left: 120px;');
		childWindow.document.writeln('}');
		childWindow.document.writeln('#apDiv1 {');
		childWindow.document.writeln('	position: absolute;');
		childWindow.document.writeln('	left: 65px;');
		childWindow.document.writeln('	top: 4px;');
		childWindow.document.writeln('	width: 281px;');
		childWindow.document.writeln('	height: 217px;');
		childWindow.document.writeln('	z-index: 1;');
		childWindow.document.writeln('}');
		childWindow.document.writeln('#apDiv2 {');
		childWindow.document.writeln('	position: absolute;');
		childWindow.document.writeln('	left: 358px;');
		childWindow.document.writeln('	top: 6px;');
		childWindow.document.writeln('	width: 615px;');
		childWindow.document.writeln('	height: 214px;');
		childWindow.document.writeln('	z-index: 2;');
		childWindow.document.writeln('	font-family: "Times New Roman", Times, serif;');
		childWindow.document.writeln('	font-size: 36px;');
		childWindow.document.writeln('	font-weight: bold;');
		childWindow.document.writeln('	text-align: center;');
		childWindow.document.writeln('}');
		childWindow.document.writeln('#apDiv3 {');
		childWindow.document.writeln('	position: absolute;');
		childWindow.document.writeln('	left: 910px;');
		childWindow.document.writeln('	top: 10px;');
		childWindow.document.writeln('	width: 196px;');
		childWindow.document.writeln('	height: 27px;');
		childWindow.document.writeln('	z-index: 3;');
		childWindow.document.writeln('	font-family: Georgia, "Times New Roman", Times, serif;');
		childWindow.document.writeln('}');
		childWindow.document.writeln('</style>');
		childWindow.document.writeln('<script type="text/javascript">');
		childWindow.document.writeln('	function space( space ) {');
		childWindow.document.writeln('		for ( var i = 0 ; i < space ; i = i + 1 ) { ');
		childWindow.document.writeln('		document.write("&nbsp;");');
		childWindow.document.writeln('		}');
		childWindow.document.writeln('	}	');
			
		   
		childWindow.document.writeln('</script>');
		
		
		childWindow.document.writeln('</head>');
		
		childWindow.document.writeln('<body>');
		childWindow.document.writeln('<div id="apDiv1"><img src="logo.JPG" width="263" height="215" /></div>');
		childWindow.document.writeln('<div id="apDiv2">');
		childWindow.document.writeln('  <p>INFORMATION SHEET</p>');
		 childWindow.document.writeln(' <p>Jamaa Health Consultants, Inc.</p>');
		childWindow.document.writeln('</div>');
		childWindow.document.writeln('<div id="apDiv3">Client information Sheet</div>');
		childWindow.document.writeln('<form action="" method="post" name="form1" class="form_style" id="form1">');
		 childWindow.document.writeln(' <p>');
			childWindow.document.writeln('<label for="name">Name : </label>');
			 childWindow.document.write('<u>' + document.getElementById('name').value + '</u>' );
			childWindow.document.writeln('<script type="text/javascript"> space(28)</script>');
    childWindow.document.writeln(' <label for="ssn">SSN# : </label>');
			 childWindow.document.write('<u>' + document.getElementById('ssn').value + '</u>' );
			childWindow.document.writeln('<script type="text/javascript"> space(28)</script>' );
			childWindow.document.writeln('<label for="case_ref">Case Ref# : </label>' );
			 childWindow.document.write('<u>' + document.getElementById('case_ref').value + '</u>' );
		  childWindow.document.writeln('</p>' );
		  childWindow.document.writeln('<p>' );
			childWindow.document.writeln('<label>' );
			 childWindow.document.writeln(' New Client : <script type="text/javascript"> space(15)</script>' );
			   childWindow.document.writeln('<input type="radio" name="new_client" value="radio" id="new_client_0" />' );
			childWindow.document.writeln('yes</label>' );
		  
			childWindow.document.writeln('<label>' );
			childWindow.document.writeln('  <input type="radio" name="new_client" value="radio" id="new_client_1" />' );
			 childWindow.document.writeln(' no</label>' );
		 childWindow.document.writeln(' </p>' );
		 childWindow.document.writeln(' <p>' );
			childWindow.document.writeln('<label>Address change : <script type="text/javascript"> space(7)</script>' );
			childWindow.document.writeln('  <input type="radio" name="address_change" value="radio" id="address_change_0" />' );
			childWindow.document.writeln('  yes</label>' );
			childWindow.document.writeln('<label>' );
			childWindow.document.writeln('  <input type="radio" name="address_change" value="radio" id="address_change_1" />' );
			childWindow.document.writeln('  no</label>' );
		childWindow.document.writeln('</p>' );
		childWindow.document.writeln('  <p>' );
			childWindow.document.writeln('<label for="old_address">Old Address : ' );
			 childWindow.document.write('<u>' + document.getElementById('old_address').value + '</u>' );;
		 childWindow.document.writeln(' </p>' );
		  childWindow.document.writeln('<p>' );
			childWindow.document.writeln('<label for="new_address">New Address :' ); 
			 childWindow.document.write('<u>' + document.getElementById('new_address').value + '</u>' );;
			
		  childWindow.document.writeln('</p>' );
		 childWindow.document.writeln(' <p>' );
			childWindow.document.writeln('<label for="telephone">Telephone :</label>' );
		 childWindow.document.writeln('<script type="text/javascript"> space(3)</script>   ' );
		 childWindow.document.write('<u>' + document.getElementById('telephone').value + '</u>' );
		 childWindow.document.writeln('</p>' );
		 childWindow.document.writeln(' <p>' );
		 childWindow.document.writeln(' <script src="print.js"></script>' );
			childWindow.document.writeln('<input type="button" onclick="printTextArea()" value="Print"/>' );
		 childWindow.document.writeln(' </p>' );
		 childWindow.document.writeln('<p><br />    ' );
			childWindow.document.writeln('<br />' );
		 childWindow.document.writeln(' </p>' );
		 childWindow.document.writeln(' <p>&nbsp;</p>' );
		childWindow.document.writeln('</form>' );
		childWindow.document.writeln('</body>' );
		childWindow.document.writeln('</html>' );
        childWindow.print();
        childWindow.document.close();
        childWindow.close();
      }